# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    environment:
      IMAGE_NAME: fast-api-test
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.7.6

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker
      - run:
         name: Build Docker image
         command: docker build -t $IMAGE_NAME .

      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      - run:
          name: run tests
          command: docker-compose run web pytest